import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Head } from 'next/head'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Convex Testing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head></Head>
      <body className={inter.className}>
        <ConvexClientProvider>
          {children}
          <SpeedInsights />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
